import Foundation
import SQLite3

/// Runs a background pass over a bone SQLite to replace default `wiki_sections.title`
/// values with short (≤6 word) titles generated by the on-device MLX model.
///
/// ## Design
/// - The bone is queryable immediately with default titles; enrichment improves recall
///   over time as it writes better titles (title is weighted 2× in KnowledgePackRetriever).
/// - Cancellable at any point via `cancel()` — the current chunk finishes, then the
///   loop exits cleanly.
/// - Progress reported as `(completedCount, totalCount)` via the `onProgress` closure.
/// - Thermal and battery guards are delegated to `CanisMLXEngine.generateTitle`.
/// - No new dependencies: SQLite3 C API only.
actor BoneEnricher {
    static let shared = BoneEnricher()

    /// Signature for a function that generates a title from a body string.
    /// Defaults to `CanisMLXEngine.shared.generateTitle(from:model:)`.
    typealias TitleGenerator = @Sendable (String, CanisModel) async throws -> String

    private(set) var isRunning = false
    private var enrichmentTask: Task<Void, Never>?

    private typealias SQLiteDestructor = @convention(c) (UnsafeMutableRawPointer?) -> Void
    private let sqliteTransient = unsafeBitCast(-1 as Int, to: SQLiteDestructor.self)

    init() {}

    // MARK: - Public API

    /// Start the enrichment pass.
    ///
    /// Safe to call even if another pass is already running — the existing pass is
    /// cancelled first.
    ///
    /// - Parameters:
    ///   - boneURL:        Path to the `.sqlite` bone to enrich (must be writable).
    ///   - model:          The `CanisModel` to use for title generation.
    ///   - onProgress:     Called after each chunk as `(completedCount, totalCount)`.
    ///   - titleGenerator: Overridable title generator; defaults to the shared MLX engine.
    func enrich(
        boneURL: URL,
        model: CanisModel,
        onProgress: @Sendable @escaping (Int, Int) -> Void,
        titleGenerator: TitleGenerator? = nil
    ) {
        enrichmentTask?.cancel()

        isRunning = true
        let transient = sqliteTransient
        let generator: TitleGenerator = titleGenerator ?? { body, m in
            try await CanisMLXEngine.shared.generateTitle(from: body, model: m)
        }
        let task = Task(priority: .background) { [weak self] in
            defer { Task { await self?.setNotRunning() } }
            await BoneEnricher.runEnrichment(
                boneURL: boneURL,
                model: model,
                transient: transient,
                generator: generator,
                onProgress: onProgress
            )
        }
        enrichmentTask = task
    }

    /// Cancel a running enrichment pass. The current chunk finishes, then the loop exits.
    func cancel() {
        enrichmentTask?.cancel()
        enrichmentTask = nil
        isRunning = false
    }

    private func setNotRunning() {
        isRunning = false
        enrichmentTask = nil
    }

    // MARK: - Enrichment loop (static to avoid actor re-entrancy with async calls)

    private static func runEnrichment(
        boneURL: URL,
        model: CanisModel,
        transient: @escaping @convention(c) (UnsafeMutableRawPointer?) -> Void,
        generator: TitleGenerator,
        onProgress: @Sendable @escaping (Int, Int) -> Void
    ) async {
        guard FileManager.default.fileExists(atPath: boneURL.path) else { return }

        var db: OpaquePointer?
        let flags = SQLITE_OPEN_READWRITE | SQLITE_OPEN_FULLMUTEX
        guard sqlite3_open_v2(boneURL.path, &db, flags, nil) == SQLITE_OK, let db else {
            if let db { sqlite3_close(db) }
            return
        }
        defer { sqlite3_close(db) }

        let rows = loadRows(db)
        let total = rows.count
        guard total > 0 else { return }

        var completed = 0
        for (id, body) in rows {
            if Task.isCancelled { break }

            do {
                let title = try await generator(body, model)
                if Task.isCancelled { break }
                if !title.isEmpty {
                    updateTitle(db, id: id, title: title, transient: transient)
                }
            } catch CanisMLXError.backgroundExecution {
                break
            } catch CanisMLXError.thermal {
                break
            } catch {
                // Unexpected error — skip this chunk and continue.
            }

            completed += 1
            onProgress(completed, total)
        }
    }

    // MARK: - SQLite helpers

    private static func loadRows(_ db: OpaquePointer) -> [(id: String, body: String)] {
        let sql = "SELECT id, body FROM wiki_sections ORDER BY section_index ASC"
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK, let stmt else {
            return []
        }
        defer { sqlite3_finalize(stmt) }

        var rows: [(String, String)] = []
        while sqlite3_step(stmt) == SQLITE_ROW {
            let id   = sqlite3_column_text(stmt, 0).map { String(cString: $0) } ?? ""
            let body = sqlite3_column_text(stmt, 1).map { String(cString: $0) } ?? ""
            if !id.isEmpty { rows.append((id, body)) }
        }
        return rows
    }

    private static func updateTitle(
        _ db: OpaquePointer,
        id: String,
        title: String,
        transient: @escaping @convention(c) (UnsafeMutableRawPointer?) -> Void
    ) {
        let sql = "UPDATE wiki_sections SET title = ? WHERE id = ?"
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK, let stmt else { return }
        defer { sqlite3_finalize(stmt) }
        sqlite3_bind_text(stmt, 1, title, -1, transient)
        sqlite3_bind_text(stmt, 2, id,    -1, transient)
        sqlite3_step(stmt)
    }
}
